even_instruction = 'Answer "yes" if the number is even, otherwise answer "no".'
calc_instruction = 'What is the result of the expression?'
gcd_instruction = 'Find the greatest common divisor of given numbers.'
progression_instruction = 'What number is missing in the progression?'
prime_instruction = 'Answer "yes" if given number is prime. Otherwise answer "no".'
